name: Django CI

#push 될 때 마다 → 우분투에서 → 파이썬을 설치하고 → poetry, django, 등등등 종속성 설치하고 → test 를 실행한다.

on: #액션이 언제 실행되는지를 정의합니다
  push: #라면, push 할 때마다 실행합니다.

jobs: #하나의 workflow 는 여러개의 job 으로 구성됩니다. 여기서는 ci 라는 이름(id)의 job 하나만 정의하여서 사용하였습니다
  ci:
    runs-on: ubuntu-latest #job 이 실행되는 machine 을 의미합니다. github 가 제공하는 ubuntu-latest (현재 버전 20) 을 사용합니다.
    steps: #하나의 job 은 여러개의 step 으로 구성됩니다. step 은 명령을 실행하거나 다른 action 을 실행합니다.
      - name: Check out the codes
        uses: actions/checkout@v2 #실행할 action 을 가리킵니다.

      - name: Setup python environment
        id: setup-python
        uses: actions/setup-python@v2 #실행할 action 을 가리킵니다.
        with: #uses 쓸때 같이 쓸수있음, action 에 전달할 parameter 변수입니다.
          python-version: 3.8.0

      - name: Install Poetry
        run: | # 실행할 명령어입니다. 파이프라인>|<은 yml 문법 / 값이 여러줄일때 여러줄을 가진 멀티 라인 값이라는 것을 알려줘야함
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          echo "${HOME}/.poetry/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          ${HOME}/.poetry/bin/poetry install

      - name: Test python project
        run: |
          poetry run python manage.py test
          
